#!/usr/bn/env bash

export ZEPPELIN_NOTEBOOK_S3_BUCKET=$BUCKETEER_BUCKET_NAME
export ZEPPELIN_NOTEBOOK_S3_USER=zeppelin-notebook
export AWS_ACCESS_KEY_ID=$BUCKETEER_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$BUCKETEER_AWS_SECRET_ACCESS_KEY
export ZEPPELIN_PORT=$PORT
